// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtv7hz2ygR7fCngTbiMv8ci3j8y16ubjI',
    appId: '1:246930628487:web:e88cfbc43e6c0572347d22',
    messagingSenderId: '246930628487',
    projectId: 'learnfirebase-f68f0',
    authDomain: 'learnfirebase-f68f0.firebaseapp.com',
    storageBucket: 'learnfirebase-f68f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzR_7l88VCIJK4DKU8brBuzI1rGkvql18',
    appId: '1:246930628487:android:5047857020d2cadf347d22',
    messagingSenderId: '246930628487',
    projectId: 'learnfirebase-f68f0',
    storageBucket: 'learnfirebase-f68f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDCuRXXXJN1eRmPou5i7nP3nRoaT1eys',
    appId: '1:246930628487:ios:f1838af353a2754d347d22',
    messagingSenderId: '246930628487',
    projectId: 'learnfirebase-f68f0',
    storageBucket: 'learnfirebase-f68f0.appspot.com',
    iosClientId:
        '246930628487-oh5n8pc2k72hq2oak8elkv25ru4fccgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoDCuRXXXJN1eRmPou5i7nP3nRoaT1eys',
    appId: '1:246930628487:ios:f1838af353a2754d347d22',
    messagingSenderId: '246930628487',
    projectId: 'learnfirebase-f68f0',
    storageBucket: 'learnfirebase-f68f0.appspot.com',
    iosClientId:
        '246930628487-oh5n8pc2k72hq2oak8elkv25ru4fccgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebase',
  );
}
